config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :lists

  resources :elements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'shared_lists',     to: 'lists#shared_lists',     :as => 'shared_lists'
  get 'shared_list/:id',  to: 'lists#show_shared_list', :as => 'shared_list'

  get 'all_lists',        to: 'lists#all_lists',        :as => 'all_lists'
  get 'all_list/:id',     to: 'lists#show_all_list',    :as => 'all_list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :list

  validates :title, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user

  has_many :elements, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: [:show, :edit, :update, :destroy]

  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(element_params)
    @element.list_id = params[:list_id]

    respond_to do |format|
      if @element.save
        @list = @element.list
        format.html { redirect_to @list, notice: 'Element was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { redirect_to @list, error: 'An error ocurred while creating element.' }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elements/1
  # PATCH/PUT /elements/1.json
  def update
    @list = @element.list

    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to @list, notice: 'Element was successfully updated.' }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { redirect_to @list, error: 'An error ocurred while updating element.' }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @list = @element.list
    @element.destroy
    respond_to do |format|
      format.html { redirect_to @list, notice: 'Element was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
      @list = @element.list rescue nil
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(:element).permit(:title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :show_shared_list, :show_all_list, :edit, :update, :destroy]
  before_action :set_elements, only: [:show, :show_shared_list, :show_all_list]

  # GET /lists
  # GET /lists.json
  def index
    @type_view = 'index'
    @lists = List.where('lists.user_id = ?', current_user.id)
  end

  def shared_lists
    @type_view = 'shared'
    @lists = List.where('lists.user_id = ?', current_user.id)

    render 'index'
  end

  def all_lists
    @type_view = 'all'
    @lists = List.where('lists.user_id = ?', current_user.id)

    render 'index'
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @type_view = 'mine'
  end

  def show_shared_list
    @type_view = 'shared'

    render 'show'
  end

  def show_all_list
    @type_view = 'all'

    render 'show'
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    def set_elements
      @elements = @list.elements
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/elements/_form.html.erb
<%= form_with(model: element, local: true) do |form| %>
  <% if element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% element.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text"><%= form.label :title %></span>
    </div>
    <%= form.text_field :title, id: :element_title, class: "form-control" %>
  </div>

  <div class="btn btn-success">
    <%= form.submit %>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Editing Element</h1>

<%= render 'form', element: @element %>

<%= link_to 'Back', @list, class: "btn btn-primary btn-lg btn-xlarge" %>

app/views/home/index.html.erb
<div class="center jumbotron">
  <h1>TODO APP</h1>
  <% unless current_user %>
    <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary btn-lg btn-xlarge" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-default btn-lg btn-xlarge" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Todoapp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <!--%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %-->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <!--%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %-->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <!--%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %-->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <!--%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %-->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <!--%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %-->

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Todoapp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "My lists", lists_path  %></li>
            <li><%= link_to "Shared with me", shared_lists_path  %></li>
            <li><%= link_to "All my lists", all_lists_path  %></li>
          </ul>
          <% if current_user %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary btn-lg btn-xlarge sign-out-button" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text"><%= form.label :title %></span>
    </div>
    <%= form.text_field :title, id: :list_title, class: "form-control", :required => true %>
  </div>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text"><%= form.label :description %></span>
    </div>
    <%= form.text_area :description, id: :list_description, class: 'form-control' %>
  </div>

  <div class="btn btn-success">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list, class: "btn btn-primary btn-lg btn-xlarge" %>
<%= link_to 'Back', lists_path, class: "btn btn-primary btn-lg btn-xlarge" %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <% if @type_view == 'index' %>
    My lists
  <% elsif @type_view == 'shared' %>
    Shared with me
  <% elsif @type_view == 'all' %>
    All my lists
  <% end %>
</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <% if @type_view == 'index' %>
        <th>Edit</th>
        <th>Delete</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <% if @type_view == 'index' %>
          <td><%= link_to list.title, list %></td>
        <% elsif @type_view == 'shared' %>
          <td><%= link_to list.title, shared_list_path(list) %></td>
        <% elsif @type_view == 'all' %>
          <td><%= link_to list.title, all_list_path(list) %></td>
        <% end %>
        <td><%= list.description %></td>
        <% if @type_view == 'index' %>
          <td><%= link_to '', edit_list_path(list), class: "fa fa-pencil fa-2x option-icon option-edit" %></td>
          <td><%= link_to '', list, method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-trash-o fa-2x option-icon option-delete" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @type_view == 'index' %>
  <%= link_to 'New List', new_list_path, class: "btn btn-primary btn-lg btn-xlarge" %>
<% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path, class: "btn btn-primary btn-lg btn-xlarge" %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @list.title %></h1>

<p>
  <%= @list.description %>
</p>

<h2>Elements</h2>

<% if @type_view == 'mine' %>
  <%= form_tag elements_path, remote: true, method: :post do %>
    <%= text_field_tag :list_id, @list.id, class: "form-control", :type => 'hidden' %>
    <div class="input-group mb-3">
      <%= text_field_tag 'element[title]', '', class: "form-control", :placeholder => "Element title", :required => true %>
      <div class="input-group-append">
        <%= button_tag(type: :submit, class: 'btn btn-outline-secondary') do %>
          Add element
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Element</th>
      <% if @type_view == 'mine' %>
        <th>Edit</th>
        <th>Delete</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @elements.each do |element| %>
      <tr>
        <td><%= element.title %></td>
        <% if @type_view == 'mine' %>
          <td><%= link_to '', edit_element_path(element), class: "fa fa-pencil fa-2x option-icon option-edit" %></td>
          <td><%= link_to '', element, method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-trash-o fa-2x option-icon option-delete" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @type_view == 'mine' %>
  <%= link_to 'Edit', edit_list_path(@list), class: "btn btn-primary btn-lg btn-xlarge" %>
<% end %>

<% if @type_view == 'mine' %>
  <%= link_to 'Back', lists_path, class: "btn btn-primary btn-lg btn-xlarge" %>
<% elsif @type_view == 'shared' %>
  <%= link_to 'Back', shared_lists_path, class: "btn btn-primary btn-lg btn-xlarge" %>
<% elsif @type_view == 'all' %>
  <%= link_to 'Back', all_lists_path, class: "btn btn-primary btn-lg btn-xlarge" %>
<% end %>